language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - android-28
    - add-on
    - extra
before_install:
    - yes | sdkmanager "platforms;android-28"
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
    - sdkmanager "system-images;android-26;google_apis;x86"
    - echo no | avdmanager create avd --force -n emulatorApi28 -k "system-images;android-26;google_apis;x86"
    - emulator -avd test -no-audio -no-window &
    - adb shell input keyevent 82 &
    - ./gradlew dependencies || true
before_script:
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
script:
    - ./gradlew build connectedCheck
    - "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
before_cache:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
cache:
    directories:
        -$HOME/.gradle/caches/
        -$HOME/.gradle/wrapper/s
licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'